import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertCircle, ArrowDownRight, ArrowUpRight, BarChart3, CheckCircle2, CircleAlert, Coins, LoaderCircle, RefreshCw, RotateCcw, ShoppingBag, Users } from 'lucide-react';
import { fetchAnalytics, fetchAnalyticsShops, filtersFromSearch, mergeAnalyticsFilters, peso } from '../../lib/adminAnalytics';
import type { AnalyticsFilters, AnalyticsPayload, AnalyticsShopOption, RankedMetric } from '../../types/adminAnalytics';
import { usePortalRealtimeRefresh } from '../../realtime/usePortalRealtimeRefresh';
import './analytics.css';

type RangeKey = '30' | '90' | 'year' | 'custom';
type RankingTab = 'products' | 'shops' | 'categories';
type RevenueMode = 'netRevenue' | 'grossRevenue';
const EMPTY: AnalyticsPayload = { summary: { grossRevenue: 0, refunds: 0, netRevenue: 0, paidOrders: 0, averageOrderValue: 0, purchasingCustomers: 0, repeatCustomers: 0, repeatCustomerRate: 0, cancellationRate: 0, problematicOrders: 0 }, comparisonSummary: null, series: [], paymentStatuses: [], deliveryStatuses: [], products: [], shops: [], categories: [] };
const COLORS = ['#2E7D32', '#B66A1B', '#2563EB', '#7C3AED', '#DC2626'];

function manilaToday() { const p = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Manila', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); const v = (t: string) => p.find(x => x.type === t)?.value || ''; return `${v('year')}-${v('month')}-${v('day')}`; }
function shiftDate(date: string, days: number) { const result = new Date(`${date}T00:00:00Z`); result.setUTCDate(result.getUTCDate() + days); return result.toISOString().slice(0, 10); }
function baseFilters(): AnalyticsFilters { const endDate = manilaToday(); return { startDate: shiftDate(endDate, -29), endDate, granularity: 'day' }; }
function preset(key: Exclude<RangeKey, 'custom'>) { const endDate = manilaToday(); return key === 'year' ? { startDate: `${endDate.slice(0, 4)}-01-01`, endDate } : { startDate: shiftDate(endDate, key === '30' ? -29 : -89), endDate }; }
function rangeOf(filters: AnalyticsFilters): RangeKey { for (const key of ['30', '90', 'year'] as const) { const r = preset(key); if (r.startDate === filters.startDate && r.endDate === filters.endDate) return key; } return 'custom'; }
function message(error: unknown) { const text = error instanceof Error ? error.message : ''; return /super_admin|permission|42501/i.test(text) ? 'Analytics is available only to Super Administrators.' : 'Analytics could not be loaded. Please try again.'; }
function delta(now: number, before?: number) { return before == null || before === 0 ? null : ((now - before) / before) * 100; }

function Kpi({ label, detail, value, current, previous, icon: Icon }: { label: string; detail: string; value: string; current: number; previous?: number; icon: typeof Coins }) { const change = delta(current, previous); return <article className="analytics-kpi"><div className="analytics-kpi__title"><span><Icon aria-hidden="true" /></span><div><small>{label}</small><em>{detail}</em></div></div><strong>{value}</strong><p className={change == null ? '' : change >= 0 ? 'up' : 'down'}>{change == null ? 'No prior data' : <>{change >= 0 ? <ArrowUpRight aria-hidden="true" /> : <ArrowDownRight aria-hidden="true" />}{Math.abs(change).toFixed(1)}% vs previous</>}</p></article>; }
function Empty({ text }: { text: string }) { return <div className="analytics-empty"><BarChart3 aria-hidden="true" /><p>{text}</p></div>; }
function Health({ title, rows }: { title: string; rows: { name: string; value: number }[] }) { const total = rows.reduce((n, row) => n + Number(row.value), 0); return <section className="analytics-panel analytics-health"><header><h2>{title}</h2><span>{total.toLocaleString()} orders</span></header>{rows.length ? <div>{rows.map((row, index) => { const pct = total ? (Number(row.value) / total) * 100 : 0; return <article key={row.name}><p><i style={{ background: COLORS[index % COLORS.length] }} /><strong>{row.name}</strong><span>{Number(row.value).toLocaleString()} · {pct.toFixed(1)}%</span></p><b><i style={{ width: `${pct}%`, background: COLORS[index % COLORS.length] }} /></b></article>; })}</div> : <Empty text="No data for this period." />}</section>; }
function Leaders({ tab, rows }: { tab: RankingTab; rows: RankedMetric[] }) { const max = Math.max(...rows.map(row => Number(row.revenue || 0)), 0); const link = tab === 'products' ? '/admin/products' : tab === 'shops' ? '/admin/artisans' : ''; return rows.length ? <div className="analytics-leaders__scroll"><table><thead><tr><th>{tab === 'products' ? 'Product' : tab === 'shops' ? 'Shop' : 'Category'}</th><th>Revenue</th><th>Units</th><th>Orders</th>{tab === 'products' && <th>Shop</th>}{tab === 'categories' && <th>Views</th>}</tr></thead><tbody>{rows.map((row, i) => <tr key={`${row.name}-${i}`}><td><span>{i + 1}</span>{link ? <Link to={link}>{row.name}</Link> : <strong>{row.name}</strong>}<i><b style={{ width: `${max ? Number(row.revenue || 0) / max * 100 : 0}%` }} /></i></td><td>{peso(row.revenue)}</td><td>{Number(row.units_sold || row.unitsSold || 0).toLocaleString()}</td><td>{Number(row.orders || 0).toLocaleString()}</td>{tab === 'products' && <td>{row.shop_name || row.shopName || '—'}</td>}{tab === 'categories' && <td>{Number(row.views || 0).toLocaleString()}</td>}</tr>)}</tbody></table></div> : <Empty text="No performance data for the selected period." />; }

export default function AnalyticsPage() {
  const [search, setSearch] = useSearchParams(); const hasInitialised = useRef(false); const sequence = useRef(0);
  const defaults = useMemo(baseFilters, []); const searchKey = search.toString(); const parsed = useMemo(() => filtersFromSearch(search), [searchKey]); const filters = useMemo(() => parsed.startDate && parsed.endDate ? parsed : { ...parsed, ...defaults }, [defaults, parsed]);
  const [data, setData] = useState<AnalyticsPayload>(EMPTY); const [shops, setShops] = useState<AnalyticsShopOption[]>([]); const [hasLoaded, setHasLoaded] = useState(false); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const [shopError, setShopError] = useState(false); const [updated, setUpdated] = useState<Date | null>(null); const [tab, setTab] = useState<RankingTab>('products'); const [revenueMode, setRevenueMode] = useState<RevenueMode>('netRevenue'); const [showOrders, setShowOrders] = useState(true); const [dateError, setDateError] = useState('');
  const update = useCallback((patch: Partial<AnalyticsFilters>) => setSearch(mergeAnalyticsFilters(new URLSearchParams(searchKey), { ...filters, ...patch })), [filters, setSearch, searchKey]);
  const load = useCallback(async () => { const request = ++sequence.current; if (hasLoaded) setRefreshing(true); try { const result = await fetchAnalytics(filters); if (request === sequence.current) { setData(result); setUpdated(new Date()); setError(''); setHasLoaded(true); } } catch (cause) { if (request === sequence.current) setError(message(cause)); } finally { if (request === sequence.current) setRefreshing(false); } }, [filters, hasLoaded, searchKey]);
  useEffect(() => { if (!hasInitialised.current && (!parsed.startDate || !parsed.endDate)) { hasInitialised.current = true; setSearch(mergeAnalyticsFilters(new URLSearchParams(searchKey), filters), { replace: true }); } }, [filters, parsed.endDate, parsed.startDate, searchKey, setSearch]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { void fetchAnalyticsShops().then(setShops).catch(() => setShopError(true)); }, []); usePortalRealtimeRefresh(['orders', 'products', 'shops'], load, 500);
  const range = rangeOf(filters); const chooseRange = (key: RangeKey) => { setDateError(''); if (key !== 'custom') update(preset(key)); }; const changeDate = (key: 'startDate' | 'endDate', value: string) => { const next = { ...filters, [key]: value }; if (next.startDate && next.endDate && next.startDate > next.endDate) return setDateError('Choose an end date on or after the start date.'); setDateError(''); update({ [key]: value }); };
  const summary = data.summary; const compare = data.comparisonSummary; const rows = data[tab]; const filterChips = [filters.shopId ? shops.find(shop => shop.id === filters.shopId)?.name || 'Selected shop' : '', filters.orderType ? `${filters.orderType === 'customized' ? 'Custom' : 'Product'} orders` : '', filters.granularity !== 'day' ? `${filters.granularity} chart` : ''].filter(Boolean);
  return <main className="analytics-page"><header className="analytics-page__header"><aside><b className={refreshing ? 'refreshing' : ''}>{refreshing ? <LoaderCircle aria-hidden="true" /> : <CheckCircle2 aria-hidden="true" />}{refreshing ? 'Refreshing' : 'Live data'}</b>{updated && <small>Updated {updated.toLocaleTimeString('en-PH', { hour: 'numeric', minute: '2-digit' })}</small>}<button type="button" onClick={() => void load()} disabled={refreshing}><RefreshCw aria-hidden="true" />Refresh</button></aside></header>
    <section className="analytics-filters" aria-label="Analytics filters"><div className="analytics-ranges">{(['30', '90', 'year', 'custom'] as RangeKey[]).map(key => <button type="button" key={key} aria-pressed={range === key} onClick={() => chooseRange(key)}>{key === 'custom' ? 'Custom' : key === 'year' ? 'This year' : `Last ${key} days`}</button>)}</div><div className="analytics-fields">{range === 'custom' && <><label><span>From</span><input type="date" value={filters.startDate || ''} onChange={e => changeDate('startDate', e.target.value)} /></label><label><span>To</span><input type="date" value={filters.endDate || ''} onChange={e => changeDate('endDate', e.target.value)} /></label></>}<label><span>Shop</span><select value={filters.shopId || ''} onChange={e => update({ shopId: e.target.value || undefined })}><option value="">All shops</option>{shops.map(shop => <option value={shop.id} key={shop.id}>{shop.name}</option>)}</select>{shopError && <em>Shop names unavailable.</em>}</label><label><span>Order type</span><select value={filters.orderType || ''} onChange={e => update({ orderType: e.target.value || undefined })}><option value="">All orders</option><option value="product">Product orders</option><option value="customized">Custom orders</option></select></label><label><span>Chart period</span><select value={filters.granularity} onChange={e => update({ granularity: e.target.value as AnalyticsFilters['granularity'] })}><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option></select></label></div>{dateError && <p className="analytics-date-error" role="alert"><AlertCircle aria-hidden="true" />{dateError}</p>}{filterChips.length > 0 && <footer>{filterChips.map(chip => <button key={chip} type="button" onClick={() => chip === 'Selected shop' || shops.some(shop => shop.name === chip) ? update({ shopId: undefined }) : chip.includes('orders') ? update({ orderType: undefined }) : update({ granularity: 'day' })}>{chip} ×</button>)}<button type="button" className="clear" onClick={() => { setDateError(''); setSearch(mergeAnalyticsFilters(search, defaults)); }}><RotateCcw aria-hidden="true" />Clear filters</button></footer>}</section>
    {error && !hasLoaded ? <section className="analytics-state" role="alert"><CircleAlert aria-hidden="true" /><h2>Analytics couldn’t load</h2><p>{error}</p><button type="button" onClick={() => void load()}>Try again</button></section> : <>{error && <p className="analytics-error">{error} <button onClick={() => void load()}>Retry</button></p>}<section className="analytics-kpis">{hasLoaded ? <><Kpi label="Net revenue" detail="Collected less refunds" value={peso(summary.netRevenue)} current={summary.netRevenue} previous={compare?.netRevenue} icon={Coins} /><Kpi label="Gross revenue" detail="Paid and completed orders" value={peso(summary.grossRevenue)} current={summary.grossRevenue} previous={compare?.grossRevenue} icon={BarChart3} /><Kpi label="Refunds" detail="Completed refund amounts" value={peso(summary.refunds)} current={summary.refunds} previous={compare?.refunds} icon={RotateCcw} /><Kpi label="Paid orders" detail="Orders with confirmed payment" value={summary.paidOrders.toLocaleString()} current={summary.paidOrders} previous={compare?.paidOrders} icon={ShoppingBag} /><Kpi label="Average order" detail="Net revenue per paid order" value={peso(summary.averageOrderValue)} current={summary.averageOrderValue} previous={compare?.averageOrderValue} icon={Users} /><Kpi label="Customers" detail="Buyers who placed an order" value={summary.purchasingCustomers.toLocaleString()} current={summary.purchasingCustomers} previous={compare?.purchasingCustomers} icon={Users} /></> : Array.from({ length: 6 }).map((_, i) => <div className="analytics-kpi skeleton" key={i}><i /><i /><i /></div>)}</section>
    <section className="analytics-primary"><section className="analytics-panel analytics-chart-panel"><header><div><h2>Revenue and orders</h2><p>Track sales through the selected period.</p></div><div className="analytics-chart-controls"><span><button type="button" aria-pressed={revenueMode === 'netRevenue'} onClick={() => setRevenueMode('netRevenue')}>Net</button><button type="button" aria-pressed={revenueMode === 'grossRevenue'} onClick={() => setRevenueMode('grossRevenue')}>Gross</button></span><label><input type="checkbox" checked={showOrders} onChange={e => setShowOrders(e.target.checked)} />Orders</label></div></header>{!hasLoaded ? <div className="analytics-chart skeleton"><i /></div> : data.series.length ? <><div className="analytics-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.series}><defs><linearGradient id="revenueFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#a65318" stopOpacity=".32" /><stop offset="1" stopColor="#a65318" stopOpacity="0" /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eee4da" /><XAxis dataKey="period" tick={{ fontSize: 11, fill: '#857469' }} axisLine={false} tickLine={false} /><YAxis yAxisId="money" tickFormatter={v => `₱${Number(v) >= 1000 ? `${(Number(v) / 1000).toFixed(0)}k` : v}`} tick={{ fontSize: 11, fill: '#857469' }} axisLine={false} tickLine={false} /><YAxis hide={!showOrders} yAxisId="orders" orientation="right" tick={{ fontSize: 11, fill: '#857469' }} axisLine={false} tickLine={false} /><Tooltip formatter={(value, name) => [String(name) === 'Orders' ? Number(value).toLocaleString() : peso(value), String(name)]} /><Legend /><Area yAxisId="money" type="monotone" dataKey={revenueMode} name={revenueMode === 'netRevenue' ? 'Net revenue' : 'Gross revenue'} stroke="#934308" strokeWidth={2.5} fill="url(#revenueFill)" /><Area hide={!showOrders} yAxisId="orders" type="monotone" dataKey="orders" name="Orders" stroke="#2563eb" strokeWidth={2} fill="transparent" /></AreaChart></ResponsiveContainer></div><p className="sr-only">{data.series.length} trend points; total revenue is {peso(data.series.reduce((sum, point) => sum + Number(point[revenueMode]), 0))}.</p></> : <Empty text="No paid orders for the selected period." />}</section><aside className="analytics-panel analytics-insights"><header><h2>Customer</h2><Users aria-hidden="true" /></header><Insight label="Repeat customers" value={`${summary.repeatCustomers.toLocaleString()} buyers`} detail={`${(summary.repeatCustomerRate * 100).toFixed(1)}% of purchasing customers`} tone="good" /><Insight label="Cancellation rate" value={`${(summary.cancellationRate * 100).toFixed(1)}%`} detail="of paid orders" tone={summary.cancellationRate > .1 ? 'warn' : 'good'} /><Insight label="Problematic orders" value={summary.problematicOrders.toLocaleString()} detail="requiring attention" tone={summary.problematicOrders ? 'alert' : 'good'} /></aside></section>
    <section className="analytics-health-grid"><Health title="Payment" rows={data.paymentStatuses} /><Health title="Fulfillment" rows={data.deliveryStatuses} /></section><section className="analytics-panel analytics-leaders"><header><div><h2>Performance leaders</h2><p>Ranked by paid-order revenue.</p></div></header><nav role="tablist"><button role="tab" aria-selected={tab === 'products'} onClick={() => setTab('products')}>Products</button><button role="tab" aria-selected={tab === 'shops'} onClick={() => setTab('shops')}>Shops</button><button role="tab" aria-selected={tab === 'categories'} onClick={() => setTab('categories')}>Categories</button></nav><Leaders tab={tab} rows={rows} /></section></>}</main>;
}
function Insight({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: 'good' | 'warn' | 'alert' }) { return <article className={`analytics-insight ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
